spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: file://E:/spring-kafka-cqrs/git-microservices-demo/microservices-demo/config-server-repository
          clone-on-start: true
    fail-fast: true

server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG